app/blog/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.routers import DefaultRouter

from . import views
from . import api

api_router = DefaultRouter()
api_router.register(r'pages', api.PageViewSet)
api_router.register(r'posts', api.PostViewSet)

beep_urlpatterns = patterns('',
    url(r'^$', views.BeepList.as_view(), name='blog_beep_list'),
    url(r'^new/$', views.BeepCreate.as_view(), name='blog_beep_new'),
    url(r'^edit/(?P<pk>\d+)/$', views.BeepUpdate.as_view(), name='blog_beep_edit'),
    url(r'^view/(?P<pk>\d+)/$', views.BeepDetail.as_view(), name='blog_beep_detail'),
    url(r'^delete/(?P<pk>\d+)/$', views.BeepDelete.as_view(), name='blog_beep_delete'),
)

urlpatterns = patterns('blog.views',
    # General
    url(r'^index/$', 'index', name='blog_index'),
    url(r'^contact/$', 'contact', name='blog_contact'),
    url(r'^contact/document/$', 'document', name='blog_document'),
    url(r'^subscribe/$', 'subscribe', name='blog_subscribe'),
    # Pages
    url(r'^pages/$', 'pages', name='blog_pages'),
    url(r'^page/(?P<page_slug>[\w-]+)/$', 'page', name='blog_page'),
    # Posts
    url(r'^posts/$', 'posts', name='blog_posts'),
    url(r'^post/(?P<post_id>[0-9]+)/(?P<post_slug>[\w-]+)/$', 'post', name='blog_post'),
    # Beep
    url(r'^beep/', include(beep_urlpatterns)),
    # Search
    url(r'^search/$', 'search', name='blog_search'),
    # API
    url(r'^api/', include(api_router.urls)),
)

app/core/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.views.decorators.cache import cache_page
from django.templatetags.static import static
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views

from . import sitemaps as core_sitemaps

admin.autodiscover()

# Root url patterns
urlpatterns = patterns('',
    # Admin and 3rd party applications
    url(r'^language/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^plugin/ckeditor/', include('ckeditor.urls')),
    url(r'^plugin/select/', include('django_select2.urls')),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    # Core
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^error/400/$', 'core.views.error_400', name='error_400'),
    url(r'^error/403/$', 'core.views.error_403', name='error_403'),
    url(r'^error/404/$', 'core.views.error_404', name='error_404'),
    url(r'^error/500/$', 'core.views.error_500', name='error_500'),
    url(r'^debug/$', 'core.views.debug', name='debug'),
    url(r'^static-page/$', TemplateView.as_view(template_name='user/core/static_page.html'), name='static_page'),
    # Applications
    url(r'^blog/', include('blog.urls')),
    # SEO
    url(r'^favicon\.ico$', RedirectView.as_view(url=static('favicon.ico'), permanent=True), name="favicon.ico"),
    url(r'^robots\.txt$', RedirectView.as_view(url=static('robots.txt'), permanent=True), name="robots.txt"),
    url(r'^sitemap\.xml$',
        cache_page(60 * 10)(sitemaps_views.index),  # cache for 10 minutes
        {'sitemaps': core_sitemaps.sitemaps_dict}),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(60 * 10)(sitemaps_views.sitemap),  # cache for 10 minutes
        {'sitemaps': core_sitemaps.sitemaps_dict}),
)

# Serve static files
urlpatterns += patterns('',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

# Serve media files
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

# Configure error handlers
handler400 = 'core.views.error_400'  # Request cannot be fulfilled due to bad syntax
handler403 = 'core.views.error_403'  # Server refuses to respond to request
handler404 = 'core.views.error_404'  # Requested resource could not be found
handler500 = 'core.views.error_500'  # Server generic error message

app/blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User

from core import abstracts
from core.utils import helpers


def get_blog_file_name(instance, filename):
    return helpers.get_file_filename(instance, filename, "blog")


def get_blog_document_file_name(instance, filename):
    return helpers.get_file_filename(instance, filename, "blog/documents")


''' Types '''

ITEM_STATUS_PUBLISHED = 1
ITEM_STATUS_HIDDEN = 2
ITEM_STATUS_CHOICES = (
    (ITEM_STATUS_PUBLISHED, "Published"),
    (ITEM_STATUS_HIDDEN, "Hidden"),
)

''' Slider '''


class Slider(abstracts.ModelAbstract):
    status = models.IntegerField(max_length=9, choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)

    def __unicode__(self):
        return self.__str__()


class Slide(abstracts.ModelAbstract):
    status = models.IntegerField(max_length=9, choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(max_length=1024, null=True, blank=True, upload_to=get_blog_file_name)
    related_slider = models.ForeignKey(Slider)

    def __str__(self):
        return u"{}".format(self.title)

    def __unicode__(self):
        return self.__str__()


''' Page '''


class Widget(abstracts.ModelAbstract):
    title = models.CharField(max_length=32)
    content = models.TextField()
    featured_image = models.ImageField(max_length=1024, null=True, blank=True, upload_to=get_blog_file_name)
    link_title = models.CharField(max_length=32, null=True, blank=True)
    link_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)

    def __unicode__(self):
        return self.__str__()


class Page(abstracts.ModelAbstract):
    status = models.IntegerField(max_length=9, choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    slug = models.SlugField(unique=True, editable=False)
    content = models.TextField()
    widgets = models.ManyToManyField(Widget, null=True, blank=True)
    featured_image = models.ImageField(max_length=1024, null=True, blank=True, upload_to=get_blog_file_name)
    related_slider = models.ForeignKey(Slider, null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)

    def __unicode__(self):
        return self.__str__()

    def get_widgets(self):
        return self.widgets.all()

    def save(self, *args, **kwargs):
        self.slug = helpers.get_slug(self.title)
        super(Page, self).save(*args, **kwargs)


''' Post '''


class Category(abstracts.ModelAbstract):
    title = models.CharField(max_length=32)
    slug = models.SlugField(unique=True, editable=False)
    description = models.CharField(max_length=512, null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)

    def __unicode__(self):
        return self.__str__()

    def save(self, *args, **kwargs):
        self.slug = helpers.get_slug(self.title)
        super(Category, self).save(*args, **kwargs)


class Post(abstracts.ModelAbstract):
    status = models.IntegerField(max_length=9, choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    slug = models.SlugField(editable=False)
    short_content = models.CharField(max_length=512)
    full_content = models.TextField()
    categories = models.ManyToManyField(Category)
    featured_image = models.ImageField(max_length=1024, null=True, blank=True, upload_to=get_blog_file_name)
    related_slider = models.ForeignKey(Slider, null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)

    def __unicode__(self):
        return self.__str__()

    def save(self, *args, **kwargs):
        self.slug = helpers.get_slug(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_post', kwargs={'post_id': self.pk, 'post_slug': self.slug})


''' Beep '''


class Beep(abstracts.ModelAbstract):
    text = models.TextField(max_length=128)
    user = models.ForeignKey(User, null=True, blank=True)
    length = models.IntegerField(null=True, blank=True, editable=False, )

    def __str__(self):
        return u"{}".format(self.text)

    def __unicode__(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse('blog_beep_edit', kwargs={'pk': self.pk})

    def save(self, force_insert=False, force_update=False, using=None,
            update_fields=None):
        if (update_fields and 'text' in update_fields) or (not update_fields):
            self.length = len(self.text)
        super(Beep, self).save(force_insert, force_update, using, update_fields)


''' Subscriber & Document '''


class Subscriber(abstracts.ModelAbstract):
    name = models.CharField(max_length=32)
    email = models.EmailField(unique=True)

    def __str__(self):
        return u"{} ({})".format(self.name, self.email)

    def __unicode__(self):
        return self.__str__()


class Document(abstracts.ModelAbstract):
    name = models.CharField(max_length=32)
    email = models.EmailField()
    short_description = models.CharField(max_length=128)
    document_file = models.FileField(upload_to=get_blog_document_file_name)

    def __str__(self):
        return u"'{0}' attached document with '{1}' description".format(self.name, self.short_description)

    def __unicode__(self):
        return self.__str__()


''' Contact '''


class Contact(abstracts.ModelAbstract):
    name = models.CharField(max_length=32)
    email = models.EmailField()
    subject = models.CharField(max_length=32)
    message = models.TextField()

    def __str__(self):
        return u"'{0}' submit contact with '{1}' subject".format(self.name, self.subject)

    def __unicode__(self):
        return self.__str__()

app/blog/forms.py
from django import forms

from . import models


class BeepForm(forms.ModelForm):
    class Meta:
        models = models.Beep
        field = '__all__'


class DocumentForm(forms.ModelForm):
    class Meta:
        model = models.Document
        fields = '__all__'


class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = '__all__'


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = models.Subscriber
        fields = ['name', 'email', ]

app/blog/views.py
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.contrib import messages
from django import forms as django_forms
from django.views.decorators.cache import cache_page
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from core import abstracts
from core.utils.decorators import log
from . import models
from . import forms
from . import logic


class BeepList(abstracts.NeverCacheMixin, ListView):
    template_name = "user/blog/beep_list.html"
    model = models.Beep
    paginate_by = 20

    def get_queryset(self):
        return models.Beep.objects.order_by('-modified_at').all()


class BeepCreate(abstracts.NeverCacheMixin, CreateView):
    model = models.Beep
    fields = ['text', ]
    template_name = "user/blog/beep_form.html"
    success_url = reverse_lazy('blog_beep_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BeepCreate, self).form_valid(form)


class BeepUpdate(abstracts.NeverCacheMixin, UpdateView):
    model = models.Beep
    fields = ['text', ]
    template_name = "user/blog/beep_form.html"
    success_url = reverse_lazy('blog_beep_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BeepUpdate, self).form_valid(form)


class BeepDetail(abstracts.NeverCacheMixin, DetailView):
    model = models.Beep
    template_name = "user/blog/beep_detail.html"


class BeepDelete(abstracts.NeverCacheMixin, DeleteView):
    model = models.Beep
    template_name = "user/blog/beep_confirm_delete.html"
    success_url = reverse_lazy('blog_beep_list')


@log
@cache_page(60 * 3)
def index(request, template='user/blog/index.html', context={}):
    blog_logic = logic.BlogLogic(request)

    context['pages'] = blog_logic.pages()
    context['posts'] = blog_logic.posts()
    # context['beeps'] = blog_logic.beeps()
    return render(request, template, context)


''' Pages '''


@log
def pages(request, template='user/blog/pages.html', context={}):
    blog_logic = logic.BlogLogic(request)
    context['pages'] = blog_logic.pages()
    return render(request, template, context)


@log
@cache_page(60 * 3)
def page(request, page_slug, template='user/blog/page.html', context={}):
    blog_logic = logic.BlogLogic(request)
    context['page'] = blog_logic.page(page_slug)
    return render(request, template, context)


''' Posts '''


@log
def posts(request, template='user/blog/posts.html', context={}):
    blog_logic = logic.BlogLogic(request)
    context['posts'] = blog_logic.posts()
    return render(request, template, context)


@log
@cache_page(60 * 3)
def post(request, post_id, post_slug, template='user/blog/post.html', context={}):
    blog_logic = logic.BlogLogic(request)
    context['post'] = blog_logic.post(post_id, post_slug)
    return render(request, template, context)


''' Others '''


@log
def contact(request, template="user/blog/contact.html", context={}):
    contact_form = forms.ContactForm(request.POST or None)

    if request.method == 'POST':
        if contact_form.is_valid():
            contact_form.save()
            messages.add_message(request, messages.SUCCESS, _('Your message successfully submitted.'))
            return redirect(reverse('blog_contact'))
        else:
            messages.add_message(request, messages.ERROR, _('Please fix errors bellow.'))

    context['contact_form'] = contact_form
    context['document_form'] = forms.DocumentForm()

    return render(request, template, context)


@log
def document(request, template="user/blog/contact.html", context={}):
    document_form = forms.DocumentForm(request.POST or None, request.FILES or None)

    if request.method == 'POST':
        if document_form.is_valid():
            document_form.save()
            messages.add_message(request, messages.SUCCESS, _('Your application successfully submitted.'))
            return redirect(reverse('blog_contact'))
        else:
            messages.add_message(request, messages.ERROR, _('Please fix errors bellow.'))

    context['contact_form'] = forms.ContactForm()
    context['document_form'] = document_form

    return render(request, template, context)


@log
def search(request, template='user/blog/search.html', context={}):
    blog_logic = logic.BlogLogic(request)

    term = blog_logic.grab_get_param("term")
    search_result = blog_logic.search(term)

    context['term'] = term
    context['pages'] = search_result.pages
    context['posts'] = search_result.posts
    return render(request, template, context)


@log
def subscribe(request):
    blog_logic = logic.BlogLogic(request)

    name = blog_logic.grab_get_param("name")
    email = blog_logic.grab_get_param("email")

    if not name or not email:
        messages.add_message(request, messages.ERROR, _('Please enter your name and email.'))
    else:
        try:
            django_forms.EmailField().clean(email)
            blog_logic.new_subscription(name, email)
            messages.add_message(request, messages.SUCCESS, _('You successfully subscribed.'))
        except ValidationError:
            messages.add_message(request, messages.ERROR, _('Please enter correct email.'))
        except IntegrityError:
            messages.add_message(request, messages.WARNING, _('You already have been subscribed.'))

    return redirect(request.META.get('HTTP_REFERER'))

app/files/templates/user/blog/_page_list.html
{% load thumbnail %}

<div class="row">
    {% for page in page_list %}
        <div class="col-xs-6 col-sm-3">
            <a href="{% url 'blog_page' page.slug %}">
                <img src="{{ page.featured_image|thumbnail_url:'small' }}" alt="{{ page.title }}" title="{{ page.title }}" />
                <h4>{{ page.title }}</h4>
            </a>
            <br />
            <span class="text-muted">{{ page.modified_at }}</span>
        </div>
    {% empty %}
        <h4>No pages.</h4>
    {% endfor %}
</div>

app/files/templates/user/blog/_post_list.html
{% load i18n %}
{% load thumbnail %}

<ul class="media-list">
    {% for post in post_list %}
        {% url 'blog_post' post.id post.slug as post_url %}
        <li class="media">
            <a class="pull-left" href="{{ post_url }}">
                <img class="media-object" width="128" src="{{ post.featured_image|thumbnail_url:'small' }}" alt="{{ post.title }}" title="{{ post.title }}" />
            </a>
            <div class="media-body">
                <h4 class="media-heading">
                    <a href="{{ post_url }}">{{ post.title }}</a>
                    <small class="text-muted">{{ post.modified_at }}</small>
                </h4>
                {{ post.short_content }}
            </div>
        </li>
    {% empty %}
        <h4>{% blocktrans %}No posts.{% endblocktrans %}</h4>
    {% endfor %}
</ul>

app/files/templates/user/blog/_slider.html
{% load thumbnail %}

<div id="application-bootstrap-carousel" class="carousel slide" data-ride="carousel">
    {# Indicators #}
    <ol class="carousel-indicators">
        {% for slide in slider.slide_set.all %}
            <li data-target="#slide-{{ forloop.counter0 }}" data-slide-to="{{ forloop.counter0 }}"
                    {% if forloop.counter0 == 0 %} class="active" {% endif %}></li>
        {% endfor %}
    </ol>

    {# Wrapper for slides #}
    <div class="carousel-inner">
        {% for slide in slider.slide_set.all %}
            <div {% if forloop.counter0 == 0 %} class="item active" {% else %} class="item" {% endif %}>
                <img src="{{ slide.image|thumbnail_url:'xxl' }}"
                     alt="{{ slide.title }}" title="{{ slide.title }}" />
                <div class="carousel-caption">
                    <h3>{{ slide.title }}</h3>
                    <p>{{ slide.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    {# Controlls #}
    <a class="left carousel-control" href="#application-bootstrap-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#application-bootstrap-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

app/files/templates/user/blog/beep_confirm_delete.html
{% extends 'user/layout.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Delete beep" %}</h1>
    <form method="post">
        {% csrf_token %}
        {% blocktrans with item=object %}
            Are you sure you want to delete "{{ item }}"?
        {% endblocktrans %}
        <br />
        <input type="submit" value="{% trans "Submit" %}" />
    </form>
{% endblock %}

app/files/templates/user/blog/beep_detail.html
{% extends 'user/layout.html' %}
{% load i18n %}
{% load humanize %}
{% load format %}

{% block content %}
    <h1>{% trans "Beeps" %}</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="pull-right">
                <a href="{% url "blog_beep_edit" object.id %}">{% trans "edit" %}</a>
                <a href="{% url "blog_beep_delete" object.id %}">{% trans "delete" %}</a> |
                <a href="{% url "blog_beep_list" %}">{% trans "back to list" %}</a>
            </div>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="thumbnails clearfix">
                <div class="thumbnail pull-left" style="margin-right: 20px;">
                    <p class="text-info">
                        #{{ object.id }}&nbsp;{{ object.text }}
                    </p>
                    <span class="text-muted">{{ object.modified_at|naturaltime }}</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/beep_form.html
{% extends 'user/layout.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Modify beep" %}</h1>
    {% include 'user/_form.html' with form=form method="POST" %}
{% endblock %}

app/files/templates/user/blog/beep_list.html
{% extends 'user/layout.html' %}
{% load i18n %}
{% load humanize %}
{% load format %}

{% block content %}
    <h1>{% trans "Beeps" %}</h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'blog_beep_new' %}" class="pull-right">{% trans "New" %}</a>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="thumbnails clearfix">
                {% for item in object_list %}
                    <div class="thumbnail pull-left" style="margin-right: 20px;">
                        <p class="text-info">
                            #{{ item.id }}&nbsp;{{ item.text }}
                        </p>
                        <span class="text-muted">{{ item.modified_at|naturaltime }}</span>
                        <div>
                            <a href="{% url "blog_beep_detail" item.id %}">{% trans "view" %}</a>
                            <a href="{% url "blog_beep_edit" item.id %}">{% trans "edit" %}</a>
                            <a href="{% url "blog_beep_delete" item.id %}">{% trans "delete" %}</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}&{{ request.GET|dict_as_request_params:"page" }}">{% trans "previous" %}</a>
                    {% endif %}

                    <span class="current">
                        {% blocktrans with page_number=page_obj.number page_count=paginator.num_pages %}
                            page {{ page_number }} of {{ page_count }}
                        {% endblocktrans %}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}&{{ request.GET|dict_as_request_params:"page" }}">{% trans "next" %}</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/contact.html
{% extends 'user/layout.html' %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>{% blocktrans %}Contact us{% endblocktrans %}</h1>
            {% url 'blog_contact' as blog_contact %}
            {% include "user/_form.html" with form=contact_form action=blog_contact method="post" %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>{% blocktrans %}Also you can submit your application:{% endblocktrans %}</h3>
            {% url 'blog_document' as blog_document %}
            {% include "user/_form.html" with form=document_form action=blog_document method="post" %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>{% blocktrans %}And, also you can subscribe:{% endblocktrans %}</h3>
            <form class="form-inline" role="form" action="{% url 'blog_subscribe' %}" method="get">
                <input id="name" name="name" type="text" class="form-control" placeholder="{% trans "Your name..." %}">
                <input id="email" name="email" type="text" class="form-control" placeholder="{% trans "Your email..." %}">
                <button type="submit" class="btn btn-default">{% trans "Subscribe" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/index.html
{% extends 'user/layout.html' %}
{% load i18n %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>{% trans "Pages" %}</h2>
            {% include 'user/blog/_page_list.html' with page_list=pages %}
            <hr />
            <a href="{% url 'blog_pages' %}" class="pull-right">{% trans 'See all pages' %}</a>
        </div>
        <div class="col-md-12">
            <h2>{% trans "Posts" %}</h2>
            {% include 'user/blog/_post_list.html' with post_list=posts %}
            <hr />
            <a href="{% url 'blog_posts' %}" class="pull-right">{% trans 'See also posts' %}</a>
        </div>
        <div class="col-md-12">
            <h2>{% trans "Beeps" %}</h2>
            {% include 'user/blog/_post_list.html' with post_list=posts %}
            <hr />
            <a href="{% url 'blog_beep_list' %}" class="pull-right">{% trans 'See also beeps' %}</a>
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/page.html
{% extends 'user/layout.html' %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if page.featured_image %}
                <img src="{{ page.featured_image|thumbnail_url:'medium' }}" title="{{ page.title }}" />
            {% endif %}
            <h1>{{ page.title }}</h1>
            <p>
                {{ page.content|safe }}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% if page.related_slider %}
                {% include "user/blog/_slider.html" with slider=page.related_slider %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        {% for widget in page.widgets.all %}
            <div class="col-md-4">
                <h2>{{ widget.title }}</h2>
                {% if widget.featured_image %}
                    <img src="{{ widget.featured_image|thumbnail_url:'small' }}" alt="{{ widget.title }}" title="{{ widget.title }}" />
                {% endif %}
                <p>{{ widget.content }}</p>
                {% if widget.link_title %}
                    <a href="{{ widget.link_url }}" class="pull-right">{{ widget.link_title }}</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/files/templates/user/blog/pages.html
{% extends 'user/layout.html' %}
{% load i18n %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>{% trans "Pages" %}</h2>
            {% include 'user/blog/_page_list.html' with page_list=pages %}
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/post.html
{% extends 'user/layout.html' %}
{% load i18n %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div>
                {% if post.featured_image %}
                    <img src="{{ post.featured_image|thumbnail_url:'medium' }}" title="{{ post.title }}" />
                {% endif %}
                <h2>{{ post.title }}</h2>
                <p>{{ post.modified_at }}</p>
                <p>
                    {{ post.full_content|safe }}
                </p>

                {% if post.related_slider %}
                    {% include "user/blog/_slider.html" with slider=post.related_slider %}
                {% endif %}

                <h3>{% trans "Categories" %}</h3>
                {% for category in post.categories.all %}
                    <div class="col-md-3">
                        <h4>{{ category.title }}</h4>
                        <p>{{ category.description }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/posts.html
{% extends 'user/layout.html' %}
{% load i18n %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>{% trans "Posts" %}</h2>
            {% include 'user/blog/_post_list.html' with post_list=posts %}
        </div>
    </div>
{% endblock %}

app/files/templates/user/blog/search.html
{% extends 'user/layout.html' %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>"{{ q }}" {% blocktrans %}search result:{% endblocktrans %}</h1>
        </div>
    </div>
    <div class="col-md-12">
        <h2>{% trans "Pages" %}</h2>
        <div class="row">
            {% for page in pages %}
                <div class="col-xs-6 col-sm-3">
                    <h4><a href="{% url 'blog_page' page.slug %}">{{ page.title }}</a></h4>
                    <span class="text-muted">{{ page.modified_at }}</span>
                </div>
            {% empty %}
                <h4>{% blocktrans %}No pages found.{% endblocktrans %}</h4>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-12">
        <h2>{% trans "Posts" %}</h2>
        {% for post in posts %}
            <div class="list-group">
                <a href="{% url 'blog_post' post.id post.slug %}" class="list-group-item">
                    <h4 class="list-group-item-heading">{{ post.title }}</h4>
                    <p class="list-group-item-text">{{ post.short_content }}</p>
                </a>
            </div>
        {% empty %}
            <h4>{% blocktrans %}No posts found.{% endblocktrans %}</h4>
        {% endfor %}
    </div>
{% endblock %}